version: '2.1'


services:


  ui:
    build: .
    image: hasli/ui


  build-env:
    build:
      context: .
      dockerfile: Dockerfile.build
    image: hasli/ui-build-env


  build-war:
    image: maven:3.5.0-jdk-8
    volumes:
      - ./:/usr/src/hasli-ui
      - ~/.gradle/caches:/root/.gradle/caches
      - ~/.gradle/wrapper:/root/.gradle/wrapper
      - ~/.gradle/gradle.properties:/root/.gradle/gradle.properties
    working_dir: /usr/src/hasli-ui
    command: bash -c "./gradlew clean build"


  prepare-release:
    extends:
      service: unit
    command: bash -c "./gradlew prepareForRelease"


  release:
    extends:
      service: unit
    command: bash -c "./gradlew clean releaseBom build artifactoryPublish -Pversion=${RELEASE_VERSION} -Dmaven.home=/usr/share/maven"

