version: '2.1'

services:

  proxy:
    extends:
      file: common-services.yml
      service: proxy
    links:
      - ui
      - web-services
    ports:
      - 80:80
      - 443:443


  ui:
    image: "sunshower/ui:${UI_VERSION}"
    environment: 
      - KEYSTORE_PASSWORD=mzlapQ123
    volumes: 
      - ./resources/nginx/certs:/keys


  web-services:
    extends:
      file: common-services.yml
      service: web-services
    links:
      - db
    environment: 
      - KEYSTORE_PASSWORD=mzlapQ123
    volumes: 
      - ./resources/nginx/certs:/keys


  db:
    extends:
      file: common-services.yml
      service: db
