version: '2.1'


services:


  proxy:
    extends:
      file: common-services.yml
      service: proxy
    ports:
      - 80
    volumes:
      - ./resources/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro

  ui:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: hasli/ui-dev
    ports:
      - 9000
    volumes:
      - ./:/usr/src/
      - ~/.jspm:/root/.jspm
      - ~/.gradle/caches:/root/.gradle/caches
      - ~/.gradle/wrapper:/root/.gradle/wrapper
      - ~/.gradle/gradle.properties:/root/.gradle/gradle.properties


  web-services:
    extends:
      file: common-services.yml
      service: web-services
    links:
      - db
    ports:
      - 8443


  db:
    extends:
      file: docker-compose.yml
      service: db
    ports:
      - 5432
