version: '3'

services:

  proxy-dev:
    container_name: "proxy-dev"
    image: "nginx:1.11.1"
    ports:
      - "32770:80"
      - "32771:443"
    links:
      - ui-dev
      - web-services-dev
      - docs-dev
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro

  ui-dev:
    container_name: "ui-dev"
    image: "hasli/ui-dev:latest"
    volumes:
      - ../:/usr/src/
      - ~/.jspm:/root/.jspm
      - ~/.gradle/wrapper:/root/.gradle/wrapper

  docs:
    container_name: "hasli-${DOCS_NAME}"
    image: "hasli/docs:latest"

  web-services:
    container_name: "web-services-dev"
    image: "hasli/web-services:latest"
    links:
      - db

  db:
    container_name: "db"
    image: "postgres:9.6"
