version: '3'

services:

  proxy:
      container_name: "proxy"
      image: "nginx:1.11.1"
      ports:
        - "80:80"
        - "443:443"
      links:
        - ui
        - web-services
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  ui:
    container_name: "ui"
    image: "${UI_IMAGE}:${UI_VERSION}"

  web-services:
    container_name: "web-services"
    image: "${WEB_IMAGE}:${WEB_VERSION}"
    links:
      - db

  db:
    container_name: "db"
    image: "postgres:9.6"

  docs:
    container_name: "docs"
    image: "hasli/docs:latest"