version: '3'

services:

  proxy:
      container_name: "proxy-${UI_NAME}"
      image: "nginx:1.11.1"
      ports:
        - "80"
        - "443"
      links:
        - ui
        - web-services
        - docs
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  ui:
    container_name: "ui-${UI_NAME}"
    image: "${UI_IMAGE}:${UI_VERSION}"

  web-services:
    container_name: "web-services-${UI_NAME}"
    image: "${WEB_IMAGE}:${WEB_VERSION}"
    links:
      - db

  db:
    container_name: "db"
    image: "postgres:9.6"

  docs:
    container_name: "docs-${UI_NAME}"
    image: "${DOCS_IMAGE}:${DOCS_VERSION}"