version: '3'

services:

  proxy-dev:
    container_name: "proxy-dev"
    image: "nginx:1.11.1"
    ports:
      - "32770:80"
      - "32771:443"
    links:
      - hasli-ui-dev
      - hasli-web-dev
      - hasli-docs-dev
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro

  hasli-web-dev:
    container_name: "hasli-web-dev"
    image: "hasli-web/web:latest"

  hasli-ui-dev:
    container_name: "hasli-ui-dev"
    image: "hasli-ui/ui-dev:latest"
    volumes:
      - ../:/usr/src/
      - ~/.jspm:/root/.jspm
      - ~/.gradle/wrapper:/root/.gradle/wrapper

  hasli-docs-dev:
    container_name: "hasli-docs-${HASLI_DOCS_NAME}"
    image: "hasli-docs/docs:latest"
