server:
  port: 8443
  servlet-path: /
  context-path: /
  ssl:
    key-store: classpath:keystore.jks
    key-store-type: JKS
    key-alias: hasli.io
    key-store-path: classpath:keystore.jks
    key-store-password: h4s1!43v3r!
